version: '3'
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Deliveries
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - 3306:3306
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      
    depends_on:
      - mysql
    ports:
      - 8081:8080
networks:
  default:
    external : true
    name: delivery-network